version: 2.1
executors:
  my-executor:
    environment:
      CUSTOM_ENV: executor
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
jobs:
  first-job:
    docker:
      - image: alpine:3.7
#    executor: my-executor
    steps:
      - run:
          name: Get env
          command: |
          echo 'export CUSTOM_ENV=command' >> $BASH_ENV
          source $BASH_ENV
          echo $CUSTOM_ENV
      - run:
#          environment:
#            CUSTOM_ENV: run
          name: Get Env with set env in run
          command: echo $CUSTOM_ENV
  second-job:
    executor: my-executor
    steps:
      - run:
          name: Get env
          command: echo $CUSTOM_ENV
#      - run:
#          name: default shell test
#          command: |
#            echo 'default shell!'
#            cd /test
#            echo 'This is the default shell test with set e'
#      - run:
##          when: always
#          name: default shell with pipe
#          command: |
#            pwd
#            ls -al
#            cd /test | echo 'this is a pipe'
  third-job:
#    executor: my-executor
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo hello world
      - checkout
      - run:
          name: Running tests
          command: echo test runing


workflows:
  version: 2
  one:
    jobs:
      - first-job
      - second-job
#          context: CUSTOM_ENV
      - third-job
#          requires:
#            - first-job
