version: 2.1
jobs:
  first-job:
    docker:
      - image: alpine:3.7
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: The First Step
          command: >
            echo 'Hello World!' &&
            echo 'This is the delivery pipeline'
      - run:
          name: the second step
          command: |
            echo 'Hello World!'
            source ~/.bash_profile
            echo 'This is the delivery pipeline'
  second-job:
    docker:
      - image: alpine:3.7
    working_directory: /build
    steps:
      - run:
          name: default shell test
          command: |
            set +e
            echo 'default shell!'
            cd /project
            echo 'This is the default shell test with set e'
      - run:
          name: default shell with pipe
          command: |
            pwd
            ls -al
            cd /project | echo 'this is a pipe'
  third-job:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo hello world
      - run:
          name: Running tests
          command: make test
      - checkout


workflows:
  version: 2
  one:
    jobs:
      - first-job
      - second-job
      - third-job
