version: 2.1
jobs:
  first-job:
    docker:
      - image: alpine:3.7
    working_directory: /build
#    environment:
#      CUSTOM_ENV: job
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "export CUSTOM_ENV='command'" >> $BASH_ENV
            echo $CUSTOM_ENV
      - run:
          name: Get Env without set locally
          command: |
            echo $CUSTOM_ENV
      - run:
          environment:
            CUSTOM_ENV: run
          name: Get Env with set env in run
          command: |
            echo $CUSTOM_ENV
  second-job:
    docker:
      - image: alpine:3.7
    working_directory: /build
    steps:
      - run:
          name: default shell test
          command: |
            set +e
            echo 'default shell!'
            cd /project
            echo 'This is the default shell test with set e'
      - run:
          name: default shell with pipe
          command: |
            set +o pipefail
            pwd
            ls -al
            cd /project | echo 'this is a pipe'
  third-job:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo hello world
      - checkout
      - run:
          name: Running tests
          command: echo test runing


workflows:
  version: 2
  one:
    jobs:
      - first-job
      - second-job
      - third-job:
          requires:
            - first-job
