version: 2.1
jobs:

  build:
#    working_directory: ~/build
    docker:
      - image: alpine:3.7
    working_directory: /mnt/ramdisk
    steps:
      - run: |
        echo '#!/bin/sh' > run.sh
        echo 'echo Hello world!' >> run.sh
        chmod +x run.sh
        - run: ./run.sh
#    steps:
#      - run:
#          name: The First Step
#          command: |
#            echo 'Hello World!'
#            echo 'This is the delivery pipeline'
#      - run:
#          name: Code Has Arrived
#          command: |
#            pwd
#            ls -al
#            echo 'That should look familiar'
