version: 2.1
executors:
  my-executor:
    environment:
      CUSTOM_ENV: executor
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
jobs:
  first-job:
    docker:
      - image: circleci/node:10.0-browsers
    #    executor: my-executor
    steps:
      - run:
          name: Get env
          command: |
            echo 'export MY_CUSTOM_ENV="command"' >> $BASH_ENV
            echo $MY_CUSTOM_ENV
      - run:
          name: Get Env with set env in run
          command: echo ${MY_CUSTOM_ENV}
      - run:
          name: Get Env twice
          command: |
            echo ${MY_CUSTOM_ENV}
            echo ${MY_CUSTOM_ENV}
  second-job:
    executor: my-executor
    steps:
      - run:
          name: Get env
          command: echo $CUSTOM_ENV
  #      - run:
  #          name: default shell test
  #          command: |
  #            echo 'default shell!'
  #            cd /test
  #            echo 'This is the default shell test with set e'
  #      - run:
  ##          when: always
  #          name: default shell with pipe
  #          command: |
  #            pwd
  #            ls -al
  #            cd /test | echo 'this is a pipe'
  third-job:
    #    executor: my-executor
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo hello world
      - checkout
      - run:
          name: Running tests
          command: echo test runing


workflows:
  version: 2
  one:
    jobs:
      - first-job
      - second-job
      #          context: CUSTOM_ENV
      - third-job
#          requires:
#            - first-job
