version: 2.1
jobs:
  first-job:
    docker:
      - image: alpine:3.7
    working_directory: /mnt/ramdisk
    steps:
      - run:
          name: the first step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
            echo "export GIT_SHA1=$CIRCLE_SHA1" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: GET ENV
          command: |
            echo 'bash_env is $BASH_ENV'
            echo 'path is $PATH'
            echo 'git is $GIT_SHA1'
  second-job:
    docker:
      - image: alpine:3.7
    working_directory: /build
    steps:
      - run:
          name: default shell test
          command: |
            set +e
            echo 'default shell!'
            cd /project
            echo 'This is the default shell test with set e'
      - run:
          name: default shell with pipe
          command: |
            set +o pipefail
            pwd
            ls -al
            cd /project | echo 'this is a pipe'
  third-job:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo hello world
      - checkout
      - run:
          name: Running tests
          command: echo test runing


workflows:
  version: 2
  one:
    jobs:
      - first-job
      - second-job
      - third-job
          requires:
            - first-job
